version: '3.9'

services:
  postgres:
    container_name: maven_postgres
    image: postgres
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=maven

